name: Publish Docker

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get tag using branch name
        run: |
          echo "TAG=$(git rev-parse --abbrev-ref HEAD)" >> $env:GITHUB_ENV
        shell: pwsh
      
      - name: Build image
        run: |
          docker build . -t viralpatel9/ncs-docker:${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: viralpatel9
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image
        run: |
          docker images
          docker push viralpatel9/basic-c-app:${{ env.TAG }}
          
      - name: Ensure project builds
        run: |
          docker create --name test viralpatel9/ncs-docker:${{ env.TAG }} 
          cd ${{github.workspace}}/test-example  
          docker cp . test:/workdir/project                                         
          docker rm test                                                            
          docker run --name test \
          -v "${PWD}:/workdir/project" \
          -w /workdir/project \
          viralpatel9/ncs-docker:${{ env.TAG }} \
          west build --build-dir /workdir/project/build . -p always -b nrf52840dk_nrf52840 --no-sysbuild -- -DCONF_FILE=prj.conf